spring:
  application:
    name: spring-websocket
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000